summary for Understanding Browser Rendering
segunolalive/frontend-weekly pull request #60
Opened 2020-10-28 15:07 UTC by Chimdiya1

# What Does This PR Do?
- Adds summary for the Understanding browser rendering session

## Github Issue Referenced
- https://github.com/segunolalive/frontend-weekly/issues/48

## Link To Session on [Frontend Weekly](https://frontendweekly.dev/)
- [Understanding Browser Rendering](https://frontendweekly.dev/sessions/understanding-browser-rendering)

fixes: #48

2020-10-28 15:17 UTC, Chimdiya1 commented
@segunolalive

2020-11-16 08:42 UTC, segunolalive requested changes
This is good.

Just make the suggested changes and we done.

2020-11-16 08:42 UTC, segunolalive commented on src/session-summaries/understanding-browser-rendering.md
> +The browser receives raw bytes of data that it does not understand, these bytes are then converted to characters depending on the character encoding specified in the HTML head tag e.g. UTF-8. These c
This is concise and clear. Thanks.

Can you change the last sentence from _The host does well `too`_ to _Enodi does well `to`_

2020-11-16 08:42 UTC, segunolalive commented on src/session-summaries/understanding-browser-rendering.md
> +What you’ll learn:
Make this a header.

## What you’ll learn:

2020-11-16 09:46 UTC, Chimdiya1 commented
done @segunolalive

2020-11-16 09:49 UTC, segunolalive approved these changes

2020-11-16 11:41 UTC, merged